on: push
jobs:
  update_packages:
    runs-on: ubuntu-latest
    steps:
      -
        name: Update packages
        run: update.sh
      -
        name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
  docker:
    needs: update_packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push (Latest)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: leifcr/rails6-kubernetes:latest
      -
        name: Build and push (Latest dev)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: leifcr/rails6-kubernetes:latest-dev
          file: "{context}/dev/Dockerfile"
      -
        name: Build and push (latest mysql8 client)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: leifcr/rails6-kubernetes:latest-mysql8-client
          file: "{context}/mysql8/Dockerfile"
      -
        name: Build and push (dev mysql8 client)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: leifcr/rails6-kubernetes:dev-mysql8-client
          file: "{context}/dev-mysql8/Dockerfile"
      -
        name: Build and push (no entry point)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: leifcr/rails6-kubernetes:latest-dev-no-entrypoint
          file: "{context}/dev-no-entry-point/Dockerfile"
